### ISSUE TITLE
Live View ignores update delay

### ISSUE THREAD

**Issue by wlfbck** [grosenberg/Fluentmark#63] opened 2021-04-12 11:41 UTC
It seems the live view is currently ignoring the update delay configurable in the settings.
Instead it seems to update as fast as it can. It even makes my eclipse lag when typing in the markdown document (presumably because of the way the updating is handled).

**Comment by grosenberg** [comment] 2021-04-12 18:00
Yes, the update delay is currently unimplemented. The entire update process is background asynchronous and should not impact the editor.

Please identify the parameters of your system and the browser being used for live view. Is the browser running on the same system as the editor or over a local network? 

Confirm that the perceived lag only present when the Live view is open.
Verify that the Pandoc and Graphviz versions are current.
Does the lag occur with all documents or just a particular document?

**Comment by wlfbck** [comment] 2021-04-12 18:55
Firefox 87, same system.

>Confirm that the perceived lag only present when the Live view is open.

Confirmed.

>Verify that the Pandoc and Graphviz versions are current.

They are, just installed this week.

> Does the lag occur with all documents or just a particular document?

It should be all documents, but i don't have any bigger documents yet. But if you look at the sample below i just made, it's incredibly noticable. If you remove the plantuml include, its better but still slightly noticable. I suppose it scales with document complexity.

```
# FluentMark

dfhdfihnfdhinfdhndfhgdfi

#asfngidsfng

#sdfgns


sfdih

@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.0.1/C4_Context.puml
bla->blub
@enduml
```

**Comment by grosenberg** [comment] 2021-04-12 22:31
Unable to reproduce on Windows 10 and Firefox / Chrome.

Fluentmark caches UML images, so unless the UML content is being changed, there is no call to PlantUML and no invocation of the include and even then only for the singular UML block being edited.

Purely a guess that your system or Eclipse instance is memory constrained: each update does require running Pandoc to convert markdown to HTML. A system pause to swap Pandoc in and part of Eclipse out could explain what you are seeing.

**Comment by wlfbck** [comment] 2021-04-13 07:28
Yes, i was working on the UML and yes that causes the freezes (and makes sense if he is creating new images each time) which occur while typing.

I still see the editor being in "standstill" when holding backspace btw. Meaning that the editor view only updates after i let go of backspace, which is not the behavior one can observe in the Java editor or other editors for normal text documents inside eclipse. 

Just increased the memory eclipse uses from the default 2GB to 4GB regardless ;)

**Comment by grosenberg** [comment] 2021-04-13 20:51
Problem was that Live view update priority was higher than that of the editor UI update priority. Fix will be in the next release.

**Closed** 2021-04-14 00:25 UTC
